### ISSUE TITLE
Do you think about using rxjava? 

### ISSUE THREAD

**Issue by Rainer-Lang** [Karumi/Rosie#44]

**Comment by pedrovgs** [comment]
I guess we could provide another module giving support for RxJava :) what do you think @Serchinastico and @flipper83 ?

**Comment by cesards** [comment]
+ 1 :-)

**Comment by Rainer-Lang** [comment]
Any progress? :)

**Comment by pedrovgs** [comment]
Nop. To be honest I'm not sure if we are going to provide support for RxJava... I'll ask again @Serchinastico @flipper83 thoughts?

**Comment by Serchinastico** [comment]
My opinion is that we don't use Rx (at least not me) so it would be weird for us to implement a solution for a problem we don't have, what's more, it'd probably end up being hard to use or just wrong because we are not familiar enough with the framework.

We are open to incoming PRs though so don't be shy and let the open source flow!

**Comment by pedrovgs** [comment]
If we are not going to implement the support for RxJava we should close this issue.

**Comment by Rainer-Lang** [comment]
@pedrovgs @Serchinastico Thanks for response. I understand - it's really complicated to implement something you don't use. ;)

**Comment by eugenio1590** [comment]
I think it would be a good idea to use Rx for the use case handler class, it actually saves a lot of work. I would just add the use of the @UseCase tags or something similar. In general, the library has a very good support for the MVP and Bussines logic, but it is somewhat short for the use of Rx. :(
