### ISSUE TITLE
Add support for persistency

### ISSUE THREAD

**Issue by pakoito** [Karumi/Rosie#50]
With the coming of N we'll all have to deal with configurationChanges when windows get resized, on top of the rotation ones. The framework doesn't currently support any way of persisting tasks or state on those configuration changes, leaving what's arguably the complicated bit to the user.

Can it be addressed by Rosie, or should we consider a 3rd party alternative? What's the architectural suggestion to maintain a Clean Architecture?

**Comment by pedrovgs** [comment]
Right now all the configuration changes are not implemented using Rosie. IMHO keep the state of the software using mechanisms as serialization, or the parcelable equivalent, could be quite risky. I've seen how developers change most of the classes in a project to implement ``Serializable`` or ``Parcelable``  just to retain the state of a HTTP request and this is not the way to go. This could finish with some performance problems, crashes due to serialization errors and memory leaks if the callback mechanism used is not handled properly. We just try to keep information during the configuration change related to the view state, an example could be the scroll position or the number of items shown in a list. 

The tasks we execute don't need to be persistent because we keep the state of the software inside the core of the system and not in top of the view implementation.

An example could be requesting information to any external service through HTTP. If you request information, then rotate the device and don't want to send another HTTP request you should cache the response data using a cache and implement this synchronization mechanism inside your software and not in top of the Android SDK. Different approaches can be used depending on the feature you are implementing, this is just one of the possibilities we have.

I'm closing this issue because this feature requested is out of the scope of this framework.
